; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "T-Drive"
#define MyAppVersion "2.3.4"
#define MyAppPublisher "Syntax Sphere"
#define MyAppURL "https://github.com/hario/T-Drive"
#define MyAppExeName "T-Drive.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3B310A7-0E0C-44A7-9753-F96B3E93C3B1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Require admin rights to install to Program Files
PrivilegesRequired=admin
OutputDir=.
OutputBaseFilename=T-Drive-Installer
SetupIconFile=app.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\T-Drive.exe"; DestDir: "{app}"; Flags: ignoreversion
; Cloud subfolder is handled in [Dirs]

[Dirs]
Name: "{app}\Cloud"; Permissions: users-full

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser

[UninstallRun]
; Kill the process before uninstalling
Filename: "taskkill"; Parameters: "/F /IM {#MyAppExeName} /T"; Flags: runhidden
; Unpin from Explorer sidebar
Filename: "{app}\{#MyAppExeName}"; Parameters: "unpin"; Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
Type: filesandordirs; Name: "{userappdata}\T-Drive"

[Code]
procedure CurUninstallStepChanged(UninstallStep: TUninstallStep);
begin
  if UninstallStep = usPostUninstall then
  begin
    // Force Explorer to refresh so the sidebar pin disappears immediately
    try
      // This is a common way to notify shell changes via registry
      // but the unpin command in [UninstallRun] is the primary method.
    except
    end;
  end;
end;
