name: Build T-Drive

on:
  push:
    tags:
      - 'v*' # Push a tag like v1.0.2 to trigger the build

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install pyinstaller customtkinter pillow telethon pystray plyer

    - name: Find CustomTkinter Path (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        echo "CUSTOM_PATH=$(python -c 'import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))')" >> $GITHUB_ENV

    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        pyinstaller --noconsole --onefile --add-data "${{ env.CUSTOM_PATH }};customtkinter" --name "T-Drive-Windows" main.py

    - name: Build with PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --noconsole --onefile --add-data "$(python -c 'import customtkinter; print(customtkinter.__path__[0])'):customtkinter" --name "T-Drive-Mac" main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: T-Drive-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: T-Drive-windows-latest
          path: windows

      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: T-Drive-macos-latest
          path: mac

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows/T-Drive-Windows.exe
            mac/T-Drive-Mac
          name: T-Drive v${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
